### ISSUE TITLE
Fatal TypeError: fileStream.endAsync is not a function

### ISSUE THREAD

**Issue by adriel** [mrnerdhair/BackblazeDownloaderJS#7]
Just a heads up to anyone else who comes here.
There is an error when the downloading finishes and it doesn't remove `_downloading.bztmp` from the end of the downloaded .zip file, but the zip is intact and extracts fine when using `unzip`.

```
409.65 GB / 409.65 GB (288.28 Mbps instantaneous, 314.11 Mbps total, ETA: a few seconds)
Download done, moving file...
Fatal TypeError: fileStream.endAsync is not a function
    at /mnt/disk1/backblaze/app.js:362:22
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/mnt/disk1/backblaze/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/mnt/disk1/backblaze/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/mnt/disk1/backblaze/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/mnt/disk1/backblaze/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/mnt/disk1/backblaze/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/mnt/disk1/backblaze/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/mnt/disk1/backblaze/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/mnt/disk1/backblaze/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/mnt/disk1/backblaze/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! backblazedownloaderjs@0.0.0 start: `node app.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the backblazedownloaderjs@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-09-01T10_24_48_096Z-debug.log
```

**Comment by mrnerdhair** [comment]
Strange, doesn't happen for me... what version of Node are you using?

**Comment by adriel** [comment]
I'm on v12.9.1

**Comment by mrnerdhair** [comment]
Hopefully #10 should sort this out.
